Repository KUclap/KUclap-review, pull requests merged in 2023-04, with the labels that each got.

#20 Updated elgohr/Publish-Docker-Github-Action to a supported version (v5)
  .github/workflows/deploy-pre-production.yml
  .github/workflows/deploy-production.yml
Labels: bug

#21 [+] fix: mgo deprecated, use mongo driver instead
  Makefile
  docker/PreProd.Dockerfile
  docker/Prod.Dockerfile
  docker/Staging.Dockerfile
  go.mod
  go.sum
  server.go
  src/config/config.go
  src/dao/answers.go
  src/dao/classes.go
  src/dao/mgo.go
  src/dao/questions.go
  src/dao/recaps.go
  src/dao/reports.go
  src/dao/reviews.go
  src/helper/filter.go
  src/models/answer.go
  src/models/classes.go
  src/models/question.go
  src/models/recap.go
  src/models/report.go
  src/models/review.go
  src/routes/admin.go
  src/routes/answer.go
  src/routes/classes.go
  src/routes/question.go
  src/routes/recap.go
  src/routes/review.go
  src/routes/setup.go
  src/storage/upload.go
  src/utillitys/initial_database.go
  src/utillitys/parse.go
Labels: bug

#23 [+] fix: mgo deprecated, use mongo driver instead
  .github/workflows/deploy-pre-production.yml
  .github/workflows/deploy-production.yml
  Makefile
  docker/PreProd.Dockerfile
  docker/Prod.Dockerfile
  docker/Staging.Dockerfile
  go.mod
  go.sum
  server.go
  src/config/config.go
  src/dao/answers.go
  src/dao/classes.go
  src/dao/mgo.go
  src/dao/questions.go
  src/dao/recaps.go
  src/dao/reports.go
  src/dao/reviews.go
  src/helper/filter.go
  src/models/answer.go
  src/models/classes.go
  src/models/question.go
  src/models/recap.go
  src/models/report.go
  src/models/review.go
  src/routes/admin.go
  src/routes/answer.go
  src/routes/classes.go
  src/routes/question.go
  src/routes/recap.go
  src/routes/review.go
  src/routes/setup.go
  src/storage/upload.go
  src/utillitys/initial_database.go
  src/utillitys/parse.go
Labels: 🎷deploy pre-production

#25 [+] fix: add cal stat review
  src/dao/reviews.go
  src/models/review.go
Labels: 🚦deploy staging

#26 [+] fix: add cal stat review
  src/dao/reviews.go
  src/models/review.go
Labels: bug, 🎷deploy pre-production

#27 [+] fix: mgo deprecated, use mongo driver instead
  .github/workflows/deploy-pre-production.yml
  .github/workflows/deploy-production.yml
  Makefile
  docker/PreProd.Dockerfile
  docker/Prod.Dockerfile
  docker/Staging.Dockerfile
  go.mod
  go.sum
  server.go
  src/config/config.go
  src/dao/answers.go
  src/dao/classes.go
  src/dao/mgo.go
  src/dao/questions.go
  src/dao/recaps.go
  src/dao/reports.go
  src/dao/reviews.go
  src/helper/filter.go
  src/models/answer.go
  src/models/classes.go
  src/models/question.go
  src/models/recap.go
  src/models/report.go
  src/models/review.go
  src/routes/admin.go
  src/routes/answer.go
  src/routes/classes.go
  src/routes/question.go
  src/routes/recap.go
  src/routes/review.go
  src/routes/setup.go
  src/storage/upload.go
  src/utillitys/initial_database.go
  src/utillitys/parse.go
Labels: bug, 🚀 deploy production
